"""add line_type to tank_line and quality_attribute to solution

Revision ID: 0a1610c3240e
Revises: a84e05f02340
Create Date: 2026-04-22 15:52:34.656434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a1610c3240e'
down_revision: Union[str, None] = 'a84e05f02340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solution', sa.Column('quality_attribute', sa.String(length=200), nullable=True))
    op.add_column('tank_line', sa.Column('line_type', sa.String(length=10), nullable=False, server_default='Line'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tank_line', 'line_type')
    op.drop_column('solution', 'quality_attribute')
    # ### end Alembic commands ###
