"""add category field to process

Revision ID: 6466b0f3fcae
Revises: 0a1610c3240e
Create Date: 2026-04-22 17:06:21.190420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6466b0f3fcae'
down_revision: Union[str, None] = '0a1610c3240e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process', sa.Column('category', sa.String(length=50), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('process', 'category')
    # ### end Alembic commands ###
